# Generated by cpp11: do not edit by hand

quad_ib <- function(nx, ny, ydown) {
  .Call(`_structuredmesh_quad_ib`, nx, ny, ydown)
}

quad_vb <- function(nx, ny, ydown, zh) {
  .Call(`_structuredmesh_quad_vb`, nx, ny, ydown, zh)
}
